# Generated by Django 5.0.4 on 2024-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolNew',
            fields=[
                ('serial', models.IntegerField(db_column='Serial')),
                ('product_name', models.CharField(db_column='Product Name', max_length=45)),
                ('generic_name', models.CharField(blank=True, db_column='Generic name', max_length=45, null=True)),
                ('formulation_type', models.CharField(db_column='Formulation Type', max_length=45)),
                ('general_info', models.CharField(blank=True, db_column='General Info', max_length=45, null=True)),
                ('batch_number', models.IntegerField(db_column='Batch Number')),
                ('batch_size', models.FloatField(blank=True, db_column='Batch Size', null=True)),
                ('qty_sampled', models.FloatField(blank=True, db_column='QTY Sampled', null=True)),
                ('mfg_date', models.DateField(db_column='MFG Date')),
                ('exp_date', models.DateField(db_column='EXP Date')),
                ('specification_number', models.CharField(db_column='Specification Number', max_length=45)),
                ('revision_number', models.CharField(db_column='Revision Number', max_length=45)),
                ('change_control_number', models.CharField(blank=True, db_column='Change Control Number', max_length=45, null=True)),
                ('effective_date', models.DateField(blank=True, db_column='Effective Date', null=True)),
                ('date_of_release', models.DateField(blank=True, db_column='Date of Release', null=True)),
                ('analysed_by', models.CharField(blank=True, db_column='Analysed By', max_length=45, null=True)),
                ('prepared_by', models.CharField(blank=True, db_column='Prepared By', max_length=45, null=True)),
                ('checked_by', models.CharField(blank=True, db_column='Checked By', max_length=45, null=True)),
                ('approved_by', models.CharField(blank=True, db_column='Approved By', max_length=45, null=True)),
                ('protocolid', models.AutoField(db_column='ProtocolID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'protocol_new',
                'db_table_comment': 'Form data in  Create Protocol.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestlistMaster',
            fields=[
                ('serial', models.AutoField(db_column='Serial', primary_key=True, serialize=False)),
                ('formulation', models.CharField(db_column='Formulation', max_length=45)),
                ('test', models.CharField(db_column='Test', max_length=45)),
            ],
            options={
                'db_table': 'testlist_master',
                'db_table_comment': 'Test list for each Formulation.',
                'managed': False,
            },
        ),
    ]
