# Generated by Django 5.0.4 on 2024-04-10 03:47

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable2',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('protocolid', models.IntegerField(db_column='ProtocolID')),
                ('formulation', models.CharField(db_column='Formulation', max_length=45)),
                ('test', models.CharField(blank=True, db_column='Test', max_length=45, null=True)),
            ],
            options={
                'db_table': 'test_table_2',
                'db_table_comment': 'Selected formulation-tests, frequency, study duration and duplicates.',
                'managed': False,
            },
            managers=[
                ('selected_formu', django.db.models.manager.Manager()),
            ],
        ),
    ]
