# Generated by Django 5.0.4 on 2024-04-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_alter_testlistmaster_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testtable3',
            fields=[
                ('serial', models.AutoField(db_column='Serial', primary_key=True, serialize=False)),
                ('protocolid', models.IntegerField(blank=True, db_column='ProtocolID', null=True)),
                ('formulation', models.CharField(blank=True, db_column='Formulation', max_length=45, null=True)),
                ('test', models.CharField(blank=True, db_column='Test', max_length=45, null=True)),
                ('frequency', models.IntegerField(blank=True, db_column='Frequency', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'testtable3',
                'managed': False,
            },
        ),
    ]
