# Generated by Django 5.0.4 on 2024-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_testtable3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleId',
            fields=[
                ('protocolid', models.IntegerField(blank=True, db_column='ProtocolID', null=True)),
                ('testid', models.IntegerField(blank=True, db_column='TestID', null=True)),
                ('sampleid', models.IntegerField(db_column='SampleID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sample_id',
                'managed': False,
            },
        ),
    ]
